/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface GamePrompt { 'prompt' : string, 'gameType' : string }
export interface Message {
  'sender' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Moment {
  'id' : bigint,
  'date' : Time,
  'caption' : string,
  'photo' : ExternalBlob,
}
export interface SpecialDate {
  'title' : string,
  'date' : Time,
  'description' : string,
  'emoji' : string,
  'category' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGamePrompt' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMoment' : ActorMethod<[string, Time, ExternalBlob], bigint>,
  'createSpecialDate' : ActorMethod<
    [string, Time, string, string, string],
    bigint
  >,
  'deleteMoment' : ActorMethod<[bigint], undefined>,
  'deleteSpecialDate' : ActorMethod<[bigint], undefined>,
  'getAllMoments' : ActorMethod<[], Array<Moment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLoveNote' : ActorMethod<[], string>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getRandomPrompt' : ActorMethod<[string], [] | [GamePrompt]>,
  'getUpcomingSpecialDates' : ActorMethod<[], Array<SpecialDate>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedGamePrompts' : ActorMethod<[], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'updateLoveNote' : ActorMethod<[string], undefined>,
  'updateMoment' : ActorMethod<[bigint, string, Time], undefined>,
  'updateSpecialDate' : ActorMethod<
    [bigint, string, Time, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];